config/routes.rb
CheTortilla::Application.routes.draw do

  devise_for :users

  resources :users
  resources :dishes
  resources :participations
  resources :events do
    resources :invitations, except:[:edit, :update]
  end

  root to: 'home#index'

  post 'invitations/accepted/:token', to: 'invitations#accepted', as: 'accepted'
  post 'invitations/reject_invitation/:token', to: 'invitations#reject_invitation', as: 'reject_invitation'
  get 'invitations/user_invitations/:user', to: 'invitations#user_invitations', as: 'user_invitations'
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  enum status: [ :invited, :chef ]

  CHEF = statuses[:chef]
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: [:show, :edit, :update, :destroy]

  # GET /participations
  def index
    @participations = Participation.all
  end

  # GET /participations/1
  def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations
  def create
    @participation = Participation.new(participation_params)

    if @participation.save
      redirect_to @participation, notice: 'Participation was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /participations/1
  def update
    if @participation.update(participation_params)
      redirect_to @participation, notice: 'Participation was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /participations/1
  def destroy
    @participation.destroy
    redirect_to participations_url, notice: 'Participation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_params
      params.require(:participation).permit(:user_id, :event_id, :status)
    end
end

app/views/participations/_form.html.slim
= form_for(@participation, :html => { :class => "form-horizontal" }) do |f|
  - if @participation.errors.any?
    .alert.alert-danger.alert-dismissable
      button.close type="button" data-dismiss="alert" aria-hidden="true" 
        | &times;
      h4= "#{pluralize(@participation.errors.count,"error")} prohibited this participation from being saved:"
      ul
        - @participation.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :user, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :user, :class => "form-control"
  .form-group
    = f.label :event, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :event, :class => "form-control"
  .form-group
    = f.label :status, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.select(:status, Participation.statuses.keys.map {|status| [status.titleize,status]}, {}, {class: "form-control"} )
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/participations/edit.html.slim
.page-header
  = link_to participations_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @participation, :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | participation

= render 'form'

app/views/participations/index.html.slim
.page-header
  = link_to new_participation_path, :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Participation
  h1
    | Listing participations

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | User
        th
          | Event
        th
          | Status
        th
        th
        th
    tbody
      - @participations.each do | participation |
        tr
          td
            = participation.user
          td
            = participation.event
          td
            = participation.status
          td
            = link_to 'Show', participation
          td
            = link_to 'Edit', edit_participation_path(participation) 
          td
            = link_to 'Destroy', participation, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/participations/new.html.slim
.page-header
  = link_to participations_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | participation

= render 'form'

app/views/participations/show.html.slim
.page-header
  = link_to participations_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_participation_path(@participation), :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show participation
dl.dl-horizontal
  dt
    | User:
  dd
    = @participation.user
  dt
    | Event:
  dd
    = @participation.event
  dt
    | Status:
  dd
    = @participation.status