config/routes.rb
CheTortilla::Application.routes.draw do

  devise_for :users

  resources :users
  resources :dishes
  resources :participations
  resources :events do
    resources :invitations, except:[:edit, :update]
  end

  root to: 'home#index'

  post 'invitations/accepted/:token', to: 'invitations#accepted', as: 'accepted'
  post 'invitations/reject_invitation/:token', to: 'invitations#reject_invitation', as: 'reject_invitation'
  get 'invitations/user_invitations/:user', to: 'invitations#user_invitations', as: 'user_invitations'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :invitations
  has_many :participations
  has_many :dishes

  scope :by_creator, ->(user){ where(user: user) }
  scope :by_participation, ->(user){ includes(:participations).where(participations: {user: user}) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events_created_by_current_user = Event.by_creator(current_user)
    @events_with_current_user_participating = Event.by_participation(current_user)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:scheduled)
    end
end

app/views/events/_form.html.slim
= form_for(@event, :html => { :class => "form-horizontal" }) do |f|
  - if @event.errors.any?
    .alert.alert-danger.alert-dismissable
      button.close type="button" data-dismiss="alert" aria-hidden="true" 
        | &times;
      h4= "#{pluralize(@event.errors.count,"error")} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :scheduled, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.datetime_select :scheduled, :class => "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/events/edit.html.slim
.page-header
  = link_to events_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @event, :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | event

= render 'form'

app/views/events/index.html.slim
.page-header
  = link_to new_event_path, :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-plus New Event
  h1 Listing events
  h3 Created by me
.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Scheduled
        th
        th
        th
        th
    tbody
      - @events_created_by_current_user.each do | event |
        tr
          td
            = event.scheduled
          td
            = link_to 'Show', event
          td
            = link_to 'Edit', edit_event_path(event)
          td
            = link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
          td
            = link_to 'pending invitations', event_invitations_path(event)

  h3 I'm joining to
.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th Scheduled
        th
    tbody
      - @events_with_current_user_participating.each do | event |
        tr
          td
            = event.scheduled
          td
            = link_to 'Show', event

app/views/events/new.html.slim
.page-header
  = link_to events_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | event

= render 'form'

app/views/events/show.html.slim
.page-header
  = link_to events_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back
  = link_to edit_event_path(@event), :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-pencil
    |  Edit
  h1
    | Show event
dl.dl-horizontal
  dt
    | Scheduled:
  dd
    = @event.scheduled
=link_to 'invite people', new_event_invitation_path(@event)