config/routes.rb
CheTortilla::Application.routes.draw do

  devise_for :users

  resources :users
  resources :dishes
  resources :participations
  resources :events do
    resources :invitations, except:[:edit, :update]
  end

  root to: 'home#index'

  post 'invitations/accepted/:token', to: 'invitations#accepted', as: 'accepted'
  post 'invitations/reject_invitation/:token', to: 'invitations#reject_invitation', as: 'reject_invitation'
  get 'invitations/user_invitations/:user', to: 'invitations#user_invitations', as: 'user_invitations'
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :event
  validates :email, presence: true, uniqueness: {scope: :event_id}
  after_create :notify_invited

  scope :by_event, ->(event) { where(event: event) }
  scope :by_email, ->(email) { where(email: email) }

  def notify_invited
    InvitationMailer.invitation_email(self).deliver
  end

  def verification_token
    token = [email, event_id, created_at, 'che tortilla beve tequila'].join
    Digest::SHA1.hexdigest(token)
  end

  def get_user_from_email_if_exists
    User.find_by_email(email)
  end

  def approve_participation(user)
    user.accept_participation(event)
    self.destroy
  end

  def self.find_by_token(token)
    invitation = nil
    Invitation.all.each do |i|
      next unless i.verification_token == token
      invitation = i
      break
    end
    invitation
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: [:show, :destroy]
  before_action :set_event, except: [:user_invitation]

  def index
    @invitations = Invitation.by_event(@event)
  end

  def user_invitations
    @invitations = Invitation.by_email(current_user.email)
  end

  def show
  end

  def new
    @invitation = @event.invitations.new
  end

  def create
    @invitation = Invitation.new(invitation_params)
    if @invitation.save
      redirect_to @event, notice: 'Invitation was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @invitation.destroy
    redirect_to @event, notice: 'Invitation was successfully destroyed.'
  end

  def accepted
    if invitation = Invitation.find_by_token(params[:token])
      if (user = invitation.get_user_from_email_if_exists)
        invitation.approve_participation(user)
        redirect_to event_path(invitation.event)
      else
        redirect_to new_user_registration_path
      end
    else
      #redirect_to error_404_path
      redirect_to root_path
    end
  end

  def reject_invitation
    if @invitation = Invitation.find_by_token(params[:token])
      raise @invitation
    else
      #redirect_to error_404_path
      redirect_to root_path
    end
  end

  private
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    def set_event
      @event = Event.find_by_id(params[:event_id])
    end

    def invitation_params
      params.require(:invitation).permit(:email, :event_id)
    end
end

app/views/invitations/_form.html.slim
= simple_form_for([@event, @invitation]) do |f|
  = f.error_notification

  .inputs
    = f.input :email
    = f.input :event_id, value: @event.id, as: :hidden
  .actions
    = f.button :submit

app/views/invitations/index.html.slim
.page-header
  = link_to new_event_invitation_path(@event), :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-plus
    |  New Invitation
  h1
    | Listing invitations

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Email
        th
          | Event
        th
        th
    tbody
      - @invitations.each do | invitation |
        tr
          td
            = invitation.email
          td
            = invitation.event
          td
            = link_to 'Show', event_invitation_path(@event, invitation)
          td
            = link_to 'Destroy', event_invitation_path(@event, invitation), method: :delete, data: { confirm: 'Are you sure?' }

app/views/invitations/new.html.slim
.page-header
  = link_to event_invitations_path(@event), :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back
  h1 New invitation

= render 'form'

app/views/invitations/show.html.slim
.page-header
  = link_to invitations_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_invitation_path(@invitation), :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show invitation
dl.dl-horizontal
  dt
    | Email:
  dd
    = @invitation.email
  dt
    | Event:
  dd
    = @invitation.event

app/views/invitations/user_invitations.html.slim
.page-header
  h1
    | Listing my invitations

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Event
        th
        th
    tbody
      - @invitations.each do | invitation |
        tr
          td
            = invitation.event
          td
            = link_to 'Show', event_invitation_path(invitation.event, invitation)
          td
            = link_to 'Destroy', event_invitation_path(invitation.event, invitation), method: :delete, data: { confirm: 'Are you sure?' }